### PR TITLE
install docker on jupyterhub container

### PR DESCRIPTION
**Pull request by moisei**
jupyterhub container should be able to execute "docker" command  in order to spawn new notebooks containers.

### CODE REVIEW

**Comment by jtyberg** [comment]
The traditional approach to running docker in docker has been to mount both the docker binary and socket into the container, [like so](https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/docker-compose.yml#L17).  Did you happen to try this approach?

**Comment by moisei** [comment]
The original issue for me was that docker notebooks containers were not created by jupyterhub.
To trace down the issue I've executed bash on jupyterhub container and I've tried to execute 'docker' and it appeared that the command does not exist.
After that I've installed docker on the container and it solved the issue.
Are you saying it would be enough to add /usr/local/bin/docker to PATH? I didn't try that.
Would this approch work even if docker host and jupyterhub cotnainer have different OS?

**Comment by jtyberg** [comment]
Yes, @moisei, I'm familiar with the link error you mention.

```
root@9bfee2c8d827:/srv/jupyterhub# docker
docker: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory

root@9bfee2c8d827:/srv/jupyterhub# ldd $(which docker)
	linux-vdso.so.1 (0x00007ffe49d9f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7aef1fa000)
	libltdl.so.7 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7aeee4e000)
	/lib64/ld-linux-x86-64.so.2 (0x0000556e101a1000)
```

It looks like docker added `libltdl7` as a dependency.  So this will be problematic for anyone trying to mount a recent `docker` binary from their Linux host into the JupyterHub container.

In the other direction, if we install `docker-engine` into the container, things will break if the version of the docker client is newer than the docker daemon on the host.

**Comment by moisei** [comment]
well, it is your call now :)

one more issue in docker-compose.yml - location of docker is assumed to be /usr/local/bin. However, on my system, it is located in /usr/bin
`svc@ubuntutemp:~/jupyter/jupyterhub-deploy-docker$ which docker
/usr/bin/docker
svc@ubuntutemp:~/jupyter/jupyterhub-deploy-docker$ docker -v
Docker version 1.12.0, build 8eab29e
svc@ubuntutemp:~/jupyter/jupyterhub-deploy-docker$ uname -ar
Linux ubuntutemp 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
svc@ubuntutemp:~/jupyter/jupyterhub-deploy-docker$
`

**Comment by jtyberg** [comment]
@moisei you are correct.  This is a reference implementation, and the primary goal is to have it work out-of-the-box with the latest and greatest.  Right now, it's busted and adding docker to the JHub container is the most straightforward way to fix it.

If `docker` is installed in the JHub container, then there's no point in mounting the binary from the host, and the [line you reference](https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/docker-compose.yml#L17) in `docker-compose.yml` should be removed.  This would solve your `which docker` issue.  Would you care to remove that line (and it's comments) as part of this PR?  If not, I'll just do it in another one.

**Comment by moisei** [comment]
@jtyberg sure, I will.

**Pull request merged**
