### PR TITLE
Remove most configuration, get this working

### PR DESCRIPTION
**Pull request by manics**
This repo is currently broken https://discourse.jupyter.org/t/jupyterhub-deploy-docker-maintainer-update/14919

I've rewritten and simplified the repo so it should now work and be easier to maintain. However it might be better to archive this repository, and make this an example under https://github.com/jupyterhub/dockerspawner/tree/main/examples (which are also out of date- we should add some tests there).

What do you think?

### CODE REVIEW

**Comment by wheeldogg** [comment]
Been struggling with getting this repo running yesterday and today. Glad I found this PR as works instantly :) Makes sense to me that this should be reviewed/merged by the admin

**Comment by wheeldogg** [comment]
My only thing would be the PRs should be smaller to more easily follow and merge. There are lots of things introduced in one go. Smaller PRS are easier as incremental improvements.

**Comment by minrk** [comment]
It is a big PR, but this repo is pretty stale, so I think a big restart to get things back in shape is fine at the moment.

**Review by minrk — APPROVED** [review]
Go ahead and merge if you're happy with it @manics

**Comment by manics** [comment]
It's a big change.... but it works so I think this is a good place to build upon.

**Pull request merged**
